<h3>Import</h3>

In [59]:
import numpy as np
arr = np.random.rand(20)

### NumPy Array

In [13]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [14]:
np.array([my_list, my_list])

array([[1, 2, 3],
       [1, 2, 3]])

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [22]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [61]:
arr.shape

(20,)

In [62]:
arr.dtype

dtype('float64')

### Linearly spaced array

In [30]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

### Numpy Identity Matrix

In [31]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Random

In [32]:
np.random.rand(5)

array([0.49685596, 0.59541171, 0.98858573, 0.28875471, 0.00736466])

In [34]:
np.random.randint(0,5)

4

In [42]:
np.random.randn(1, 5)

array([[ 1.38140783,  0.63688321, -1.30961677,  0.87908466, -0.06415586]])

### Reshape Array

In [44]:
arr = np.arange(10)
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### Max/Min + Index

In [51]:
arr = np.random.rand(10)
arr

array([0.26594394, 0.57286608, 0.00844564, 0.21525716, 0.5645465 ,
       0.29696389, 0.87217722, 0.98801579, 0.84245873, 0.33298802])

In [52]:
arr.max()

0.9880157858006369

In [53]:
arr.min()

0.00844564153860683

In [54]:
arr.argmax()

7

In [65]:
arr.argmin()

10

### Array Index/Slicing

In [66]:
arr[1:5]

array([0.60505178, 0.22279896, 0.55400188, 0.91404383])

In [67]:
arr[:5]

array([0.13385298, 0.60505178, 0.22279896, 0.55400188, 0.91404383])

In [68]:
arr[0::2]

array([0.13385298, 0.22279896, 0.91404383, 0.96281277, 0.44459805,
       0.11229787, 0.46918328, 0.82186304, 0.31054026, 0.53378719])

In [69]:
arr[2:]

array([0.22279896, 0.55400188, 0.91404383, 0.16475226, 0.96281277,
       0.25195244, 0.44459805, 0.37101175, 0.11229787, 0.12388804,
       0.46918328, 0.85524162, 0.82186304, 0.3235096 , 0.31054026,
       0.19475235, 0.53378719, 0.21548355])